brokerid: "{{ inventory_hostname | regex_search('(bridge-kafka-kafka0[1-9]\\.foo\\.bar)') | regex_replace('\\.foo\\.bar', '') | regex_replace('^bridge-kafka-kafka0', '') }}"
zookeeperinfo: bridge-kafka-zk01:2181,bridge-kafka-zk02:2181,bridge-kafka-zk03:2181
dir_path: /data/kafka-logs
